# Nodos 1.3 Bundle Definitions

[bundles.minimal]
short_name = "minimal"
nodos_version = "1.3.2.b4623"
nodos_version_linux = "1.3.0.b4294"  # Platform-specific nodos version for Linux
nodos_github_url = "https://github.com/mediaz/nodos/compare/v%%old_version%%-%%arch%%-%%os%%...v%%new_version%%-%%arch%%-%%os%%"
engine_index_url = "https://raw.githubusercontent.com/mediaz/engine-releases/main/index.json"

[[bundles.minimal.module_index_urls]]
url = "https://raw.githubusercontent.com/mediaz/nodos-index/main/index"
name = "nodos"
is_active = true

[[bundles.minimal.bundled_packages]]
name = "nos.sys.variables"
version = "1.0.1.b928"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.minimal.bundled_packages]]
name = "nos.reflect"
version = "1.7.13.b1112"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

# Platform-specific variant for Linux
[[bundles.minimal.bundled_packages]]
name = "nos.sys.variables"
version = "1.0.1.b980"
platform = "linux"

[[bundles.minimal.bundled_packages]]
name = "nos.reflect"
version = "1.6.5.b980"
platform = "linux"

[bundles.standard]
short_name = "standard"
engine_index_url = "https://raw.githubusercontent.com/mediaz/engine-releases/main/index.json"
includes = ["minimal"]

[[bundles.standard.module_index_urls]]
url = "https://raw.githubusercontent.com/mediaz/nodos-index/main/index"
name = "nodos"
is_active = true

[[bundles.standard.bundled_packages]]
name = "nos.sys.shaderc"
version = "1.1.0.b953"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.sys.vulkan"
version = "6.7.4.b738"
github_url = "https://github.com/mediaz/nos-sys-vulkan/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.sys.settings"
version = "0.3.0.b804"
github_url = "https://github.com/mediaz/nos-sys-vulkan/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.filters"
version = "1.5.5.b1037"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.math"
version = "1.9.3.b907"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.utilities"
version = "3.14.5.b1149"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.mediaio"
version = "2.7.0.b700"
github_url = "https://github.com/nodos-dev/mediaio/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.sys.mediaio"
version = "0.4.1.b669"
github_url = "https://github.com/nodos-dev/mediaio/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.webcam"
version = "1.3.2.b646"
github_url = "https://github.com/nodos-dev/webcam/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.sys.animation"
version = "1.5.2.b1018"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.animation"
version = "0.3.2.b928"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.webrtc"
version = "1.2.3.b1141"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.str"
version = "0.3.1.b1106"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.sys.device"
version = "0.3.4.b24"
github_url = "https://github.com/nodos-dev/sys-device/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.rive"
version = "0.3.0.b20"
github_url = "https://github.com/nodos-dev/rive/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.standard.bundled_packages]]
name = "nos.sample.dxapp"
version = "1.1.6.b57"
github_url = "https://github.com/nodos-dev/dx-app-sample/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"
type = "sample"

[[bundles.standard.bundled_packages]]
name = "nos.sync"
version = "3.1.1.b1023"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

# Platform-specific packages for Linux
[[bundles.standard.bundled_packages]]
name = "nos.sys.shaderc"
version = "1.1.0.b980"
platform = "linux"

[[bundles.standard.bundled_packages]]
name = "nos.sys.vulkan"
version = "6.3.6.b652"
platform = "linux"

[[bundles.standard.bundled_packages]]
name = "nos.filters"
version = "1.5.2.b980"
platform = "linux"

[[bundles.standard.bundled_packages]]
name = "nos.math"
version = "1.9.3.b980"
platform = "linux"

[[bundles.standard.bundled_packages]]
name = "nos.utilities"
version = "3.9.7.b980"
platform = "linux"

[[bundles.standard.bundled_packages]]
name = "nos.mediaio"
version = "2.5.0.b664"
platform = "linux"

[[bundles.standard.bundled_packages]]
name = "nos.sys.mediaio"
version = "0.4.0.b664"
platform = "linux"

[[bundles.standard.bundled_packages]]
name = "nos.sys.animation"
version = "1.5.1.b980"
platform = "linux"

[[bundles.standard.bundled_packages]]
name = "nos.sys.device"
version = "0.3.3.b15"
github_url = "https://github.com/nodos-dev/sys-device/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"
platform = "linux"

# Disable webcam on Linux
[[bundles.standard.bundled_packages]]
name = "nos.webcam"
disabled = true
platform = "linux"

[bundles.broadcast]
short_name = "broadcast"
engine_index_url = "https://raw.githubusercontent.com/mediaz/engine-releases/main/index.json"
includes = ["standard"]

[[bundles.broadcast.module_index_urls]]
url = "https://raw.githubusercontent.com/mediaz/nodos-index/main/index"
name = "nodos"
is_active = true

[[bundles.broadcast.bundled_packages]]
name = "nos.aja"
version = "2.7.0.b789"
github_url = "https://github.com/nodos-dev/aja/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.broadcast.bundled_packages]]
name = "nos.sys.decklink"
version = "2.2.6.b136"
github_url = "https://github.com/nodos-dev/decklink/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.broadcast.bundled_packages]]
name = "nos.decklink"
version = "1.2.18.b149"
github_url = "https://github.com/nodos-dev/decklink/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.broadcast.bundled_packages]]
name = "nos.track"
version = "1.9.3.b961"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.broadcast.bundled_packages]]
name = "nos.display"
version = "0.4.0.b52"
github_url = "https://github.com/nodos-dev/display/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

[[bundles.broadcast.bundled_packages]]
name = "nos.sys.lino"
version = "1.0.5.b1114"
github_url = "https://github.com/nodos-dev/modules/compare/build.dev-%%os%%-%%old_build%%...build.dev-%%os%%-%%new_build%%"

# Platform-specific packages for Linux
[[bundles.broadcast.bundled_packages]]
name = "nos.aja"
version = "2.5.2.b700"
platform = "linux"

[[bundles.broadcast.bundled_packages]]
name = "nos.track"
version = "1.9.3.b980"
platform = "linux"

# Disable decklink packages on Linux
[[bundles.broadcast.bundled_packages]]
name = "nos.sys.decklink"
disabled = true
platform = "linux"

[[bundles.broadcast.bundled_packages]]
name = "nos.decklink"
disabled = true
platform = "linux"

[[bundles.broadcast.bundled_packages]]
name = "nos.display"
disabled = true
platform = "linux"

[[bundles.broadcast.bundled_packages]]
name = "nos.sys.lino"
disabled = true
platform = "linux"

[bundles.ai]
short_name = "ai"
engine_index_url = "https://raw.githubusercontent.com/mediaz/engine-releases/main/index.json"
includes = ["broadcast"]

[[bundles.ai.module_index_urls]]
url = "https://raw.githubusercontent.com/mediaz/nodos-index/main/index"
name = "nodos"
is_active = true

[[bundles.ai.bundled_packages]]
name = "nos.ml.ai_nodes"
version = "1.2.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.ai.model_nodes"
version = "2.2.1.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.cuda"
version = "1.2.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.interop"
version = "2.2.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.ml.onnx"
version = "2.3.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.ml.tensors"
version = "2.3.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.ml.tokenizer"
version = "1.1.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.sys.ai"
version = "3.2.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.sys.cuda"
version = "2.2.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.sys.ai.models.depth_anything"
version = "1.0.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.sys.ai.models.depth_anything_v2"
version = "1.0.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.sys.ai.models.rmbg"
version = "1.0.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.sys.ai.models.rt4ksr"
version = "1.0.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.sys.ai.models.rvm"
version = "0.1.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[[bundles.ai.bundled_packages]]
name = "nos.sys.tensor"
version = "2.2.0.b277"
github_url = "https://github.com/mediaz/nosAI/compare/build.nodos-1.3-%%os%%-%%old_build%%...build.nodos-1.3-%%os%%-%%new_build%%"

[bundles.full]
short_name = "full"
engine_index_url = "https://raw.githubusercontent.com/mediaz/engine-releases/main/index.json"
includes = ["broadcast"]

[[bundles.full.module_index_urls]]
url = "https://raw.githubusercontent.com/mediaz/nodos-index/main/index"
name = "nodos"
is_active = true

[[bundles.full.bundled_packages]]
name = "nos.sys.ai"
version = "3.1.0.b247"

[[bundles.full.bundled_packages]]
name = "nos.sys.cuda"
version = "2.1.0.b247"

[[bundles.full.bundled_packages]]
name = "nos.sys.tensor"
version = "2.1.0.b247"

[[bundles.full.bundled_packages]]
name = "nos.ai.model_nodes"
version = "2.1.0.b247"

[[bundles.full.bundled_packages]]
name = "nos.interop"
version = "2.1.0.b247"

[[bundles.full.bundled_packages]]
name = "nos.ml.onnx"
version = "2.2.0.b247"

[[bundles.full.bundled_packages]]
name = "nos.ml.tensors"
version = "2.2.0.b247"
